user_input = input("Enter your name")
print(user_input)
print(type(user_input))
mob_no = input("enter your mob no")
print(mob_no)
print(type(mob_no))
address = input("enter your address")
print(address)
location = input("enter your location")
print(location)
pin = input("enter your pin")
print(pin)
print(type(address))
print(type(location))
print(type(pin))
