print("hi", "roja", "maner", end=".")
print("hi", "roja", "maner")
print("hi", "roja", "maner", end="_____")
print("hi", "roja", "maner")
print("hi", "roja", "maner", end=".")
print("hi", "roja", "maner", end="++")
