shopping_list = ["milk", "patato", "eggs", "bread", "rice"]
print(shopping_list)
shopping_list.append("chicken")
print(shopping_list)
shopping_list.insert(3,"paneer")
print(shopping_list)
shopping_list.extend(["biryani", "sandwich"])
print(shopping_list)
shopping_list.remove("bread")
print(shopping_list)
shopping_list.pop(4)
print(shopping_list)
shopping_list.reverse()
print(shopping_list)
shopping_list.sort()
print(shopping_list)
