name = "Devendra"
print(name)
print(type(name))
print(id(name))
print(len(name))
name = name.upper()
print(name)
name = name.lower()
print(name)
e = name.count('e')
print(e)
print(name[2])
print("------------------------------------------------------------------------------------------------------")
name1="Roja"
print(name1)
print(type(name1))
print(id(name1))
print(len(name1))
name1=name1.upper()
print(name1)
name1=name1.lower()
print(name1)
print(name1[2])