print("hi", "bye", "123", sep="_")
print("hi", "bye", "code in one line")
print("hi", "bye", "code 2", "welcome to pune", sep="_", end="___")
print("hi", "lenovo", sep="=")
print("hi", "lenovo", sep="0000")
print("hi", "bye", end="_")
print("hi", "bye", sep="_")
print("roja", "maner", end="____")
print("address ganga village hadpsar","A2", sep="==")
print("address ganga village hadpsar",end="***")
print("code002","cose001",sep="**")
print("roja","maner",end="____",sep="=")
print("hadpsar","pune",sep=".....")
print("hadpsar","pune",sep=".....")
